FROM node:21-alpine3.18 AS build

WORKDIR /app

COPY package.json .
RUN npm install --legacy-peer-deps

COPY envs/.env.test ./.env
COPY nest-cli.json .
COPY tsconfig.json .
COPY tsconfig.build.json .
COPY environment.d.ts .
COPY src .

RUN npm run build:test && \
    npm cache clean --force && \
    rm -rf /root/.npm && \
    rm tsconfig*.json && \
    rm environment.d.ts && \
    rm -rf node_modules && \
    rm -rf src

FROM node:21-alpine3.18 AS production-installation

WORKDIR /app

COPY --from=build ./app .
RUN npm install --production

FROM node:21-alpine3.18 AS ready-to-start

WORKDIR /app
COPY --from=production-installation ./app .

ENTRYPOINT ["npm", "run", "start:prod"]
