import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Main page',
  description: 'Generated by create next app',
}

export default function Main() {
  return <div>main page</div>
}
